[tool.poetry]
name = "feast-affirm"
version = "0.25"
description = "Feast - Affirm"
authors = ["Francisco Arceo", "Hao Xu"]
readme = "README.md"
packages = [{include = "feast"}]

[tool.poetry.dependencies]
python = "3.7.13"
anyio = "3.6.1"
appdirs = "1.4.4"
attrs = "22.1.0"
bowler = "0.9.0"
cachetools = "5.2.0"
certifi = "2022.9.24"
charset-normalizer = "2.1.1"
click = "8.1.3"
cloudpickle = "2.2.0"
colorama = "0.4.5"
dask = "2022.1.1"
dill = "0.3.5.1"
fastapi = "0.85.0"
fastavro = "1.6.1"
fissix = "21.11.13"
fsspec = "2022.8.2"
google-api-core = "2.10.1"
google-auth = "2.12.0"
googleapis-common-protos = "1.56.4"
grpcio = "1.49.1"
grpcio-reflection = "1.47.0"
h11 = "0.14.0"
httptools = "0.5.0"
idna = "3.4"
importlib-resources = "5.9.0"
jinja2 = "3.1.2"
jsonschema = "4.16.0"
locket = "1.0.0"
markupsafe = "2.1.1"
mmh3 = "3.0.0"
moreorless = "0.4.0"
mypy = "0.981"
mypy-extensions = "0.4.3"
numpy = "1.21.6"
packaging = "21.3"
pandas = "1.3.5"
pandavro = "1.5.2"
partd = "1.3.0"
pkgutil-resolve-name = "1.3.10"
proto-plus = "1.22.0"
protobuf = "3.20.2"
pyarrow = "8.0.0"
pyasn1 = "0.4.8"
pyasn1-modules = "0.2.8"
pydantic = "1.10.2"
pygments = "2.13.0"
pymysql = "0.9.3"
pyparsing = "3.0.9"
pyrsistent = "0.18.1"
python-dateutil = "2.8.2"
python-dotenv = "0.21.0"
pytz = "2022.2.1"
pyyaml = "6.0"
requests = "2.28.1"
rsa = "4.9"
six = "1.16.0"
sniffio = "1.3.0"
sqlalchemy = {version = "1.4.41", extras = ["mypy"]}
sqlalchemy2-stubs = "0.0.2a27"
starlette = "0.20.4"
tabulate = "0.8.10"
tenacity = "8.1.0"
toml = "0.10.2"
tomli = "2.0.1"
toolz = "0.12.0"
tqdm = "4.64.1"
typeguard = "2.13.3"
typing-extensions = "4.3.0"
urllib3 = "1.26.12"
uvicorn = {version = "0.18.3", extras = ["standard"]}
uvloop = "0.17.0"
volatile = "2.1.0"
watchfiles = "0.17.0"
websockets = "10.3"
zipp = "3.8.1"

[build-system]
requires = ["setuptools>=60", "wheel", "setuptools_scm>=6.2", "grpcio", "grpcio-tools>=1.47.0", "mypy-protobuf==3.1", "sphinx!=4.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
# Including this section is comparable to supplying use_scm_version=True in setup.py.

[tool.black]
line-length = 88
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | pb2.py
    | \.pyi
    | protos
    | sdk/python/feast/embedded_go/lib
  )/
)
'''
