[tool.poetry]
name = "feast-affirm"
version = "0.28+affirm129"
description = "Feast - Affirm"
authors = ["Francisco Arceo", "Ross Briden", "Maks Stachowiak"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.7.13"
absl-py = "1.4.0"
anyio = "3.6.2"
appdirs = "1.4.4"
attrs = "22.2.0"
bowler = "0.9.0"
cachetools = "5.3.0"
certifi = "2022.12.7"
charset-normalizer = "3.0.1"
click = "8.1.3"
cloudpickle = "2.2.1"
colorama = "0.4.6"
dask = "2021.12.0"
dill = "0.3.7"
fastapi = "0.100.1"
fastavro = "1.8.0"
fissix = "21.11.13"
fsspec = "2023.1.0"
google-api-core = "2.6.1"
google-auth = "2.22.0"
googleapis-common-protos = "1.56.2"
greenlet = "2.0.2"
grpcio-tools = "1.48.2"
grpcio = "1.51.1"
grpcio-reflection = "1.48.2"
h11 = "0.14.0"
httptools = "0.6.0"
idna = "3.4"
importlib-resources = "5.12.0"
importlib-metadata = "6.7.0"
jinja2 = "3.1.2"
jsonschema = "4.17.3"
locket = "1.0.0"
markupsafe = "2.1.3"
mmh3 = "4.0.1"
moreorless = "0.4.0"
mypy = "1.4.1"
mypy-extensions = "1.0.0"
mypy-protobuf = "3.1.0"
numpy = "1.21.6"
packaging = "23.1"
pandas = "1.3.5"
pandavro = "1.5.2"
partd = "1.4.0"
pkgutil-resolve-name = "1.3.10"
pkginfo = "1.9.6"
proto-plus = "1.22.3"
protobuf = "3.20.3"
pyarrow = "8.0.0"
pyasn1 = "0.4.8"
pyasn1-modules = "0.3.0"
pydantic = "1.10.12"
pygments = "2.15.1"
pymysql = "0.9.3"
pyparsing = "3.0.9"
pyrsistent = "0.19.3"
pyspark = "3.0.2"
python-dateutil = "2.8.2"
python-dotenv = "0.21.1"
pytz = "2023.3"
pyyaml = "5.1.1"
requests = "2.31.0"
requests-toolbelt = "0.10.1"
rsa = "4.9"
six = "1.16.0"
sniffio = "1.3.0"
sqlalchemy = {version = "1.4.49", extras = ["mypy"]}
sqlalchemy2-stubs = "0.0.2a32"
starlette = "0.27.0"
tabulate = "0.9.0"
tenacity = "8.2.2"
tensorflow-metadata = "1.9.0"
toml = "0.10.2"
tomli = "2.0.1"
toolz = "0.12.0"
tqdm = "4.65.0"
twine = "1.10.0"
typed-ast = "1.5.5"
typeguard = "4.0.1"
types-protobuf = "4.23.0.2"
typing-extensions = "4.7.1"
urllib3 = "1.26.14"
uvicorn = {version = "0.20.0", extras = ["standard"]}
uvloop = "0.17.0"
volatile = "2.1.0"
watchfiles = "0.18.1"
websockets = "10.4"
zipp = "3.14.0"


[build-system]
requires = ["setuptools>=60", "wheel", "setuptools_scm>=6.2", "grpcio==1.51.1", "grpcio-tools>=1.47.0", "mypy-protobuf==3.1", "sphinx!=4.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
# Including this section is comparable to supplying use_scm_version=True in setup.py.

[tool.black]
line-length = 88
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | pb2.py
    | \.pyi
    | protos
    | sdk/python/feast/embedded_go/lib
  )/
)
'''
