name: Build Python 3.7 with Poetry
on: 
  push:
    branches: 
      - affirm
      - 0.28-affirm
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7.13"

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1

      - name: Install Dependencies
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'
